### ISSUE TITLE
Stolen Code

### ISSUE THREAD

**Issue by cazamir** [jackzeraaaa/csgo-cheat#1]
stolen code from kakhack 🤦 atleast credit cazz fag

**Comment by jackzeraaaa** [comment]
stfu retard, i did credit him, i only used his code(which is from osiris
cheat) as a base. You have no idea what youre talking so fuck off

Em seg., 12 de dez. de 2022 às 22:05, kobra ***@***.***>
escreveu:

**Comment by cazamir** [comment]
"Credits goes to youtuber cazz for memory library and interface/netvar manager." 💀  credit him for the whole thing

**Comment by jackzeraaaa** [comment]
credit him for selfcoded gui and pasted features from uc?

Em seg., 26 de dez. de 2022 às 13:56, stellar ***@***.***>
escreveu:
